apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 987626325043.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-test
  newName: 987626325043.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-test
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
